# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20180526_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
