# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_bug_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugcomment',
            old_name='comments',
            new_name='description',
        ),
    ]
